Repository norberttak/XPanel, pull requests merged in 2023-05, with the labels that each got.

#67 Add features to FIP driver
  .github/workflows/release.yml
  CMakeLists.txt
  FIP-SDK/CMakeLists.txt
  FIP-SDK/fonts/FIPFonts.h
  FIP-SDK/fonts/convert.py
  FIP-SDK/fonts/fip-fonts.bmp
  FIP-SDK/fonts/fip-fonts.fnt
  FIP-SDK/fonts/readme.txt
  XPanel.vcxproj
  XPanel.vcxproj.filters
  doc/fip-screen.md
  src/CMakeLists.txt
  src/ConfigParser.cpp
  src/ConfigParser.h
  src/Configuration.h
  src/FIPFonts.h
  src/FIPImageLayer.cpp
  src/FIPImageLayer.h
  src/FIPLayer.cpp
  src/FIPLayer.h
  src/FIPPage.cpp
  src/FIPPage.h
  src/FIPScreen.cpp
  src/FIPScreen.h
  src/FIPTextLayer.cpp
  src/FIPTextLayer.h
  src/GenericScreen.cpp
  src/GenericScreen.h
  src/LuaHelper.cpp
  src/LuaHelper.h
  src/XPanel.cpp
  test/fip-images/bmp_test_big_image.bmp
  test/test-fip-screen-config.ini
  test/test-script.lua
  test/test.vcxproj
  test/test.vcxproj.filters
Labels: enhancement

#68 Doc update
  .github/workflows/release.yml
  README.md
  doc/Flight-Instrument-Panel-01.jpg
  doc/arduino-leonardo.jpg
  doc/configuration.md
  doc/documentation.md
  doc/documentation.pdf
  doc/fip-screen.md
  doc/lua.md
  doc/multi-panel-01.jpg
  doc/radio-panel-01.jpg
  doc/switch-panel-03.jpg
  doc/trc1000.jpg
Labels: documentation

#69 Version bump for v1.7
  CMakeLists.txt
  XPanel.vcxproj
Labels: release creation

#70 Autogenerate documentation
  .github/workflows/build-and-test.yml
  .github/workflows/release.yml
  doc/documentation.md
  doc/documentation.pdf
  doc/style.css
Labels: documentation

#72 Parser refactor
  XPanel.vcxproj
  XPanel.vcxproj.filters
  doc/documentation.md
  src/CMakeLists.txt
  src/ConfigParser.cpp
  src/ConfigParser.h
  src/GenericDisplay.cpp
  src/GenericDisplay.h
  src/IniFileParser.cpp
  src/IniFileParser.h
  test/test-fip-screen-config.ini
  test/test-valid-config.ini
  test/test.vcxproj
  test/test.vcxproj.filters
Labels: enhancement

#73 GenericScreen: add dataref array type
  src/ConfigParser.cpp
  src/FIPScreen.cpp
  src/GenericScreen.cpp
  src/GenericScreen.h
Labels: bug
